# ===================================== #
# ======== Jenkaz Action ============== #
# ===================================== #
name: "Jenkaz"
description: "Action To Trigger Jenkins Jobs From Github action"
# INFO: Inputs Section
inputs:
  jenkins-url:
    description: "url for jenkins server"
    required: true
    default: ""
  jenkins-user:
    description: "user for use to auth jenkins and trigger jobs"
    required: true
    default: ""
  jenkins-token:
    description: "user token for run jenkins account"
    required: true
    default: ""
  jenkins-job-token:
    description: "job token for job pipeline"
    required: true
    default: ""
  jenkins-job-path:
    description: "full path for trigger job after JENKINS_URL/?/buildwithParameters"
    required: true
    default: ""
  jenkins-wait:
    description: "waiting time before run the jenkins job"
    required: false
    default: ""
  jenkins-track:
    description: "track a job mode"
    required: false
    default: ""
  jenkins-timeout:
    description: "track a job timeout"
    required: false
    default: ""
# INFO: Outputs Section
outputs:
  job-url:
    description: "url for jenkins job"
# INFO: Runs Section
runs:
  using: node24
  main: "dist/index.js"
